global chipsPID
global ds9

global env

set env(PATH) $env(ASCDS_INSTALL)/bin:$env(PATH)

#set chipsPID [exec env PATH=$env(ASCDS_INSTALL)/bin:$env(PATH) startchips $ds9(title) &]
set chipsPID [exec startchips $ds9(title) &]


proc CleanUp {chipsPID windowPath} {
   # check that the window is the top path. No point in trying to kill it for
   # all sub windows
   if {$windowPath == "."} {
      exec kill -9 $chipsPID
   }
}


# cleanup the chips server
bind . <Destroy> {CleanUp $chipsPID %W}
